<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="partialmodel" nsURI="http://www.example.org/partialmodel" nsPrefix="partialmodel">
  <eClassifiers xsi:type="ecore:EClass" name="PartialModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//PSObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openworld" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AllAttributes" upperBound="-1"
        eType="#//PSAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSReference" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="psType" upperBound="3"
        eType="#//PSType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredClass" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceObject" eType="#//PSObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refs" upperBound="-1" eType="#//PSReferenceToObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//PSReferenceToAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="psType" upperBound="3"
        eType="#//PSType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageNsUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredEClass" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSAttribute" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="psType" upperBound="3"
        eType="#//PSType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VarType" eSuperTypes="#//PSType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Annotation" eType="#//Var"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MayType" eSuperTypes="#//PSType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Annotation" eType="#//May"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbsType" eSuperTypes="#//PSType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Annotation" eType="#//Abs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="May">
    <eLiterals name="MayExist"/>
    <eLiterals name="MustExist"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Abs">
    <eLiterals name="Particular"/>
    <eLiterals name="Set"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Var">
    <eLiterals name="Constant"/>
    <eLiterals name="Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSString" eSuperTypes="#//PSAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSInteger" eSuperTypes="#//PSAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSBoolean" eSuperTypes="#//PSAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSOtherAttribute" eSuperTypes="#//PSAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refferedClass" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSReferenceToObject" eSuperTypes="#//PSReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetObject" eType="#//PSObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSReferenceToAttribute" eSuperTypes="#//PSReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAttribute" eType="#//PSAttribute"/>
  </eClassifiers>
</ecore:EPackage>
